name: Playwright CI Pipeline

on:
  push:
    branches:
      - feature/*

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-type:
          - name: Smoke Tests
            grep: '@smoke'
            continue-on-error: true
          - name: Flaky Tests
            grep: '@flaky'
            continue-on-error: true
          - name: Regression Tests
            grep: '@regression'
            continue-on-error: false

    continue-on-error: ${{ matrix.test-type.continue-on-error }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npx playwright install --with-deps

      - name: Run ${{ matrix.test-type.name }}
        run: npx playwright test --grep ${{ matrix.test-type.grep }}
